### ISSUE TITLE
sonopy mfcc based on C language

### ISSUE THREAD

**Issue by Chen1399** [MycroftAI/sonopy#1]
Excuse me, sir, do you have sonopy mfcc  based on C language?

**Comment by MatthewScholefield** [comment]
No, unfortunately we don't. However, it shouldn't be too difficult to implement considering effort went into making the source code [small and easy to read](https://github.com/MycroftAI/sonopy/blob/master/sonopy.py).

**Comment by Chen1399** [comment]
There are some mfcc based on C language which don't have the same result as Sonopy mfcc. If I make Mycorft‘s result as a C project , I should find a mfcc based on C language. If not, I will get mfcc based on C language to run Mycorft model, which isn't a good idea, but also can do.

**Comment by Chen1399** [comment]
Thank you. I have write one which bsaed on C language has the same result as Sonopy mfcc.

**Comment by penrods** [comment]
Since this appears to be resolved, I'm going to go ahead and close this Issue.
