### ISSUE TITLE
[Question] Dimensionality of output & input parameters relationships

### ISSUE THREAD

**Issue by Pk13055** [MycroftAI/sonopy#3]
After playing around with the `mfcc_spec` function I've noticed something and wanted some clarification on the same.

Say I have some audio file of sampling rate `sr` and length `N * sr`. 
I have chosen the following parameters (matches librosa's defaults):
- window length: 2048
- window stride: 512
- n_fft: 2048
- n_filters: 128
- n_coeffs: 20

However, 
1. n_fft has to be `2 * window_length - 1` for dimensionality to be preserved
2. n_filters does not work unless `n_filters = window_length`
3. Memory error with these default params.

When I resolve these issues by setting the params to:
- window length: 1024
- window stride: 512
- n_fft: 2047
- n_filters: 1024
- n_coeffs: 20

It results in an mfcc output of `(374, 20, 1024)`. From what I understand, `mfcc.shape[1] = n_coeffs` and `mfcc.shape[-1] = window_length` (?) but what does `mfcc.shape[0]` correspond to? Furthermore, is there any way possible to try to replicate the librosa default params without running into memory issues?

**Comment by MatthewScholefield** [comment]
Hi, I haven't had time to test these specific parameters, but as a sanity check, can you ensure that your input is a one dimensional numpy array (ie. Ensure that there isn't some first channel that represents the mono channel)? I'm mentioning this because that can cause issues with dimensionality (so much so that we should probably add a line in there that errors on multiple dimensions).

**Comment by Pk13055** [comment]
Holy sh*t, I'm surprised how much of a difference that makes. From basically multiple seconds to under a second per record. I think I'm going to try the oriignal parameters now. I think there should be some sort of check `assert len(audio.shape) == 1` or something.

EDIT: Original parameters also work flawlessly, make sure you **always** pass `audio.ravel()` to the `mfcc_spec` function.
